name: Deploy Contínuo

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executar Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 178.156.193.212
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/projeto
            git pull origin main
            docker compose up -d --build
